# Generated by Django 5.0.1 on 2026-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_cyclecount_updated_at_stockmovement_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('stock_in', 'Stock In'), ('out', 'Stock Out'), ('stock_out', 'Stock Out'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
